[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16" }

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"
    X-Frame-Options = "DENY"

[[plugins]]
  package = "@netlify/plugin-functions"